name: Ruby

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        ruby:
        - 2.6.6
        - truffleruby-head
        task:
        - test
        - smoke
        - build
    steps:
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/checkout@v1
    - name: Run test
      run: |
        ruby -v
        gem install bundler
        bundle install --jobs 4 --retry 3
        bin/setup
        bundle exec rake ${{matrix.task}}
